import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundRoot,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing['2xl'],
      paddingBottom: Spacing['5xl'],
    },
    header: {
      marginBottom: Spacing.xl,
    },
    headerTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: Spacing.xs,
    },
    newChatButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.full,
      borderWidth: 1,
      backgroundColor: 'rgba(0,240,255,0.05)',
    },
    headerTitle: {
      color: theme.textPrimary,
      fontSize: 24,
      fontWeight: '700',
      marginBottom: Spacing.sm,
    },
    headerSubtitle: {
      color: theme.textMuted,
      fontSize: 11,
      letterSpacing: 2,
      textTransform: 'uppercase',
      fontWeight: '600',
    },
    neonLine: {
      height: 2,
      borderRadius: 1,
      marginTop: Spacing.lg,
      width: 80,
    },
    messagesContainer: {
      flex: 1,
      gap: Spacing.md,
      marginBottom: Spacing.lg,
    },
    messageWrapper: {
      maxWidth: '85%',
    },
    userMessageWrapper: {
      alignSelf: 'flex-end',
    },
    aiMessageWrapper: {
      alignSelf: 'flex-start',
    },
    messageBubble: {
      padding: Spacing.lg,
      borderRadius: BorderRadius.sm,
      borderWidth: 1,
    },
    userMessage: {
      backgroundColor: theme.backgroundTertiary,
      borderColor: theme.border,
    },
    aiMessage: {
      backgroundColor: theme.backgroundDefault,
      borderColor: theme.primary,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
    },
    messageText: {
      fontSize: 15,
      lineHeight: 22,
      color: theme.textPrimary,
    },
    messageLabel: {
      fontSize: 10,
      letterSpacing: 1.5,
      textTransform: 'uppercase',
      fontWeight: '600',
      marginBottom: Spacing.xs,
    },
    userLabel: {
      color: theme.accent,
    },
    aiLabel: {
      color: theme.primary,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: Spacing.md,
      padding: Spacing.lg,
      backgroundColor: theme.backgroundDefault,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    input: {
      flex: 1,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.sm,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      color: theme.textPrimary,
      fontSize: 15,
      minHeight: 48,
      maxHeight: 120,
    },
    sendButton: {
      width: 48,
      height: 48,
      borderRadius: BorderRadius.sm,
      borderWidth: 1,
      borderColor: theme.primary,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.4,
      shadowRadius: 12,
    },
    sendButtonDisabled: {
      borderColor: theme.border,
      shadowOpacity: 0,
    },
    emptyState: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Spacing['3xl'],
    },
    emptyIcon: {
      width: 80,
      height: 80,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1,
      borderColor: theme.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: Spacing.xl,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
    },
    emptyTitle: {
      color: theme.textPrimary,
      fontSize: 20,
      fontWeight: '700',
      marginBottom: Spacing.sm,
    },
    emptySubtitle: {
      color: theme.textMuted,
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 22,
    },
    typingIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      padding: Spacing.md,
    },
    typingDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.primary,
    },
    quickActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.sm,
      marginTop: Spacing.lg,
    },
    quickAction: {
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.lg,
      borderRadius: BorderRadius.sm,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.backgroundDefault,
    },
    quickActionText: {
      color: theme.textSecondary,
      fontSize: 13,
      fontWeight: '500',
    },
    // Guide Modal Styles
    guideOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.7)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: Spacing.lg,
    },
    guideModal: {
      width: '100%',
      maxWidth: 500,
      borderRadius: BorderRadius.xl,
      padding: Spacing.xl,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 10,
    },
    guideHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: Spacing.lg,
    },
    guideIconWrap: {
      width: 48,
      height: 48,
      borderRadius: BorderRadius.lg,
      justifyContent: 'center',
      alignItems: 'center',
    },
    guideContent: {
      marginBottom: Spacing.lg,
    },
    guidePromptWrap: {
      marginTop: Spacing.sm,
      maxHeight: 200,
      padding: Spacing.lg,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.md,
      borderWidth: 1,
      borderColor: theme.border,
    },
    guideTip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      padding: Spacing.md,
      borderRadius: BorderRadius.md,
      marginBottom: Spacing.lg,
    },
    guideActions: {
      flexDirection: 'row',
      gap: Spacing.md,
    },
    guideButton: {
      flex: 1,
      paddingVertical: Spacing.lg,
      borderRadius: BorderRadius.md,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    guideCancelButton: {
      borderWidth: 1,
    },
    guideConfirmButton: {
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
  });
};
