/**
 * AI 模型提供商配置 - 平台抽成模式
 * 
 * 商业模式：
 * 1. 所有模型都收费，没有免费模型
 * 2. 平台在商家成本价基础上加价（平台服务费）
 * 3. 用户按平台售价付费使用
 * 
 * 价格单位：厘/百万tokens（1元 = 1000厘）
 */

// ==================== 类型定义 ====================

export interface ModelProvider {
  id: string;
  name: string;
  nameEn: string;
  baseUrl: string;
  apiKeyEnv: string;
  icon: string;
  website: string;
  docs: string;
  status: 'active' | 'beta' | 'coming_soon';
  categories: ModelType[];
  features: {
    streaming: boolean;
    functionCall: boolean;
    vision: boolean;
    audio: boolean;
    tools: boolean;
  };
}

export type ModelType = 'text' | 'image' | 'audio' | 'video' | 'embedding' | 'multimodal' | 'vision';
export type ModelCategory = 'chat' | 'completion' | 'image_gen' | 'image_edit' | 'audio_transcribe' | 'audio_tts' | 'video_gen' | 'embedding';

export interface ModelConfig {
  id: string;
  code: string;
  name: string;
  provider: string;
  category: ModelType;
  type: ModelCategory;
  description?: string;
  
  // 上下文和输出限制
  contextWindow: number;
  maxOutputTokens: number;
  
  // 定价（厘/百万tokens，即 1元 = 1000厘）
  costInputPrice: number;   // 商家成本价（输入）
  costOutputPrice: number;  // 商家成本价（输出）
  sellInputPrice: number;   // 平台售价（输入）= 成本价 * (1 + platformMarkup)
  sellOutputPrice: number;  // 平台售价（输出）= 成本价 * (1 + platformMarkup)
  platformMarkup: number;   // 平台加价比例（如 0.2 表示加价 20%）
  
  // 兼容旧属性名
  inputPrice?: number;      // 别名: sellInputPrice
  outputPrice?: number;     // 别名: sellOutputPrice
  
  // 会员限制
  memberOnly?: boolean;      // 是否需要会员
  superMemberOnly?: boolean; // 是否需要超级会员
  isFree?: boolean;          // 是否免费（平台抽成模式下所有模型都不免费）
  
  // 功能特性
  features: {
    streaming: boolean;
    functionCall: boolean;
    vision: boolean;
    audio: boolean;
    jsonMode: boolean;
  };
  
  // 状态
  status: 'active' | 'deprecated' | 'beta';
  
  // 标签
  tags?: string[];
}

// ==================== 平台抽成配置 ====================

/**
 * 默认平台加价比例
 * 可根据模型类型或提供商自定义
 */
export const DEFAULT_PLATFORM_MARKUP = 0.20; // 20% 加价

/**
 * 不同类型模型的平台加价比例
 */
export const MARKUP_BY_CATEGORY: Record<string, number> = {
  text: 0.15,        // 文本模型 15%
  multimodal: 0.20,  // 多模态模型 20%
  image: 0.25,       // 图像模型 25%
  audio: 0.20,       // 音频模型 20%
  video: 0.30,       // 视频模型 30%
  embedding: 0.10,   // 向量化模型 10%
};

// ==================== 提供商配置 ====================

export const MODEL_PROVIDERS: Record<string, ModelProvider> = {
  // ============ 国际厂商 ============
  
  openai: {
    id: 'openai',
    name: 'OpenAI',
    nameEn: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    apiKeyEnv: 'OPENAI_API_KEY',
    icon: 'openai',
    website: 'https://openai.com',
    docs: 'https://platform.openai.com/docs',
    status: 'active',
    categories: ['text', 'image', 'audio', 'embedding'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: true,
      tools: true,
    },
  },
  
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic',
    nameEn: 'Anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    apiKeyEnv: 'ANTHROPIC_API_KEY',
    icon: 'robot',
    website: 'https://anthropic.com',
    docs: 'https://docs.anthropic.com',
    status: 'active',
    categories: ['text', 'multimodal'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: false,
      tools: true,
    },
  },
  
  google: {
    id: 'google',
    name: 'Google AI',
    nameEn: 'Google AI',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    apiKeyEnv: 'GOOGLE_API_KEY',
    icon: 'google',
    website: 'https://ai.google',
    docs: 'https://ai.google.dev/docs',
    status: 'active',
    categories: ['text', 'image', 'audio', 'embedding', 'multimodal'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: true,
      tools: true,
    },
  },
  
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    nameEn: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/v1',
    apiKeyEnv: 'DEEPSEEK_API_KEY',
    icon: 'brain',
    website: 'https://deepseek.com',
    docs: 'https://platform.deepseek.com/docs',
    status: 'active',
    categories: ['text'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  groq: {
    id: 'groq',
    name: 'Groq',
    nameEn: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    apiKeyEnv: 'GROQ_API_KEY',
    icon: 'bolt-lightning',
    website: 'https://groq.com',
    docs: 'https://console.groq.com/docs',
    status: 'active',
    categories: ['text', 'audio'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: true,
      tools: true,
    },
  },
  
  mistral: {
    id: 'mistral',
    name: 'Mistral AI',
    nameEn: 'Mistral AI',
    baseUrl: 'https://api.mistral.ai/v1',
    apiKeyEnv: 'MISTRAL_API_KEY',
    icon: 'wind',
    website: 'https://mistral.ai',
    docs: 'https://docs.mistral.ai',
    status: 'active',
    categories: ['text', 'embedding'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  cohere: {
    id: 'cohere',
    name: 'Cohere',
    nameEn: 'Cohere',
    baseUrl: 'https://api.cohere.ai/v1',
    apiKeyEnv: 'COHERE_API_KEY',
    icon: 'circle-nodes',
    website: 'https://cohere.com',
    docs: 'https://docs.cohere.com',
    status: 'active',
    categories: ['text', 'embedding'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  stability: {
    id: 'stability',
    name: 'Stability AI',
    nameEn: 'Stability AI',
    baseUrl: 'https://api.stability.ai/v1',
    apiKeyEnv: 'STABILITY_API_KEY',
    icon: 'palette',
    website: 'https://stability.ai',
    docs: 'https://platform.stability.ai/docs',
    status: 'active',
    categories: ['image'],
    features: {
      streaming: false,
      functionCall: false,
      vision: false,
      audio: false,
      tools: false,
    },
  },
  
  // ============ 国内厂商 ============
  
  doubao: {
    id: 'doubao',
    name: '豆包',
    nameEn: 'Doubao',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    apiKeyEnv: 'DOUBAO_API_KEY',
    icon: 'fire',
    website: 'https://www.doubao.com',
    docs: 'https://www.volcengine.com/docs/82379',
    status: 'active',
    categories: ['text', 'audio'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: true,
      tools: true,
    },
  },
  
  qwen: {
    id: 'qwen',
    name: '通义千问',
    nameEn: 'Qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/api/v1',
    apiKeyEnv: 'QWEN_API_KEY',
    icon: 'cloud',
    website: 'https://tongyi.aliyun.com',
    docs: 'https://help.aliyun.com/zh/dashscope',
    status: 'active',
    categories: ['text', 'image', 'audio', 'embedding', 'multimodal'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: true,
      tools: true,
    },
  },
  
  wenxin: {
    id: 'wenxin',
    name: '文心一言',
    nameEn: 'Wenxin',
    baseUrl: 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1',
    apiKeyEnv: 'WENXIN_API_KEY',
    icon: 'feather',
    website: 'https://yiyan.baidu.com',
    docs: 'https://cloud.baidu.com/doc/WENXINWORKSHOP',
    status: 'active',
    categories: ['text', 'image'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  zhipu: {
    id: 'zhipu',
    name: '智谱AI',
    nameEn: 'Zhipu AI',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    apiKeyEnv: 'ZHIPU_API_KEY',
    icon: 'atom',
    website: 'https://www.bigmodel.cn',
    docs: 'https://open.bigmodel.cn/dev/api',
    status: 'active',
    categories: ['text', 'image', 'embedding', 'multimodal'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: false,
      tools: true,
    },
  },
  
  moonshot: {
    id: 'moonshot',
    name: 'Moonshot',
    nameEn: 'Moonshot',
    baseUrl: 'https://api.moonshot.cn/v1',
    apiKeyEnv: 'MOONSHOT_API_KEY',
    icon: 'moon',
    website: 'https://www.moonshot.cn',
    docs: 'https://platform.moonshot.cn/docs',
    status: 'active',
    categories: ['text'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    nameEn: 'MiniMax',
    baseUrl: 'https://api.minimax.chat/v1',
    apiKeyEnv: 'MINIMAX_API_KEY',
    icon: 'infinity',
    website: 'https://www.minimaxi.com',
    docs: 'https://www.minimaxi.com/document',
    status: 'active',
    categories: ['text', 'audio', 'video'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: true,
      tools: true,
    },
  },
  
  spark: {
    id: 'spark',
    name: '讯飞星火',
    nameEn: 'iFlytek Spark',
    baseUrl: 'https://spark-api-open.xf-yun.com/v1',
    apiKeyEnv: 'SPARK_API_KEY',
    icon: 'bolt',
    website: 'https://www.xfyun.cn/doc/spark',
    docs: 'https://www.xfyun.cn/doc/spark',
    status: 'active',
    categories: ['text', 'audio'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: true,
      tools: true,
    },
  },
  
  hunyuan: {
    id: 'hunyuan',
    name: '腾讯混元',
    nameEn: 'Hunyuan',
    baseUrl: 'https://hunyuan.tencentcloudapi.com',
    apiKeyEnv: 'HUNYUAN_API_KEY',
    icon: 'yin-yang',
    website: 'https://cloud.tencent.com/product/hunyuan',
    docs: 'https://cloud.tencent.com/document/product/1729',
    status: 'active',
    categories: ['text', 'image', 'embedding', 'multimodal'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: false,
      tools: true,
    },
  },
  
  yi: {
    id: 'yi',
    name: '零一万物',
    nameEn: 'Yi',
    baseUrl: 'https://api.lingyiwanwu.com/v1',
    apiKeyEnv: 'YI_API_KEY',
    icon: 'sun',
    website: 'https://www.lingyiwanwu.com',
    docs: 'https://platform.lingyiwanwu.com/docs',
    status: 'active',
    categories: ['text'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  baichuan: {
    id: 'baichuan',
    name: '百川智能',
    nameEn: 'Baichuan',
    baseUrl: 'https://api.baichuan-ai.com/v1',
    apiKeyEnv: 'BAICHUAN_API_KEY',
    icon: 'water',
    website: 'https://www.baichuan-ai.com',
    docs: 'https://platform.baichuan-ai.com/docs',
    status: 'active',
    categories: ['text'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  // ============ 更多国际厂商 ============
  
  replicate: {
    id: 'replicate',
    name: 'Replicate',
    nameEn: 'Replicate',
    baseUrl: 'https://api.replicate.com/v1',
    apiKeyEnv: 'REPLICATE_API_KEY',
    icon: 'clone',
    website: 'https://replicate.com',
    docs: 'https://replicate.com/docs',
    status: 'active',
    categories: ['text', 'image', 'audio', 'video'],
    features: {
      streaming: true,
      functionCall: false,
      vision: true,
      audio: true,
      tools: false,
    },
  },
  
  together: {
    id: 'together',
    name: 'Together AI',
    nameEn: 'Together AI',
    baseUrl: 'https://api.together.xyz/v1',
    apiKeyEnv: 'TOGETHER_API_KEY',
    icon: 'users',
    website: 'https://together.ai',
    docs: 'https://docs.together.ai',
    status: 'active',
    categories: ['text', 'image', 'embedding'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  fireworks: {
    id: 'fireworks',
    name: 'Fireworks AI',
    nameEn: 'Fireworks AI',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    apiKeyEnv: 'FIREWORKS_API_KEY',
    icon: 'fire-flame-curved',
    website: 'https://fireworks.ai',
    docs: 'https://docs.fireworks.ai',
    status: 'active',
    categories: ['text', 'image', 'audio'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: true,
      tools: true,
    },
  },
  
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    nameEn: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    apiKeyEnv: 'PERPLEXITY_API_KEY',
    icon: 'magnifying-glass',
    website: 'https://perplexity.ai',
    docs: 'https://docs.perplexity.ai',
    status: 'active',
    categories: ['text'],
    features: {
      streaming: true,
      functionCall: false,
      vision: false,
      audio: false,
      tools: false,
    },
  },
  
  xai: {
    id: 'xai',
    name: 'xAI (Grok)',
    nameEn: 'xAI',
    baseUrl: 'https://api.x.ai/v1',
    apiKeyEnv: 'XAI_API_KEY',
    icon: 'x-twitter',
    website: 'https://x.ai',
    docs: 'https://docs.x.ai',
    status: 'active',
    categories: ['text'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  meta: {
    id: 'meta',
    name: 'Meta AI (Llama)',
    nameEn: 'Meta AI',
    baseUrl: 'https://api.meta.ai/v1',
    apiKeyEnv: 'META_API_KEY',
    icon: 'meta',
    website: 'https://ai.meta.com',
    docs: 'https://ai.meta.com/llama',
    status: 'active',
    categories: ['text', 'image', 'multimodal'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: false,
      tools: true,
    },
  },
  
  ai21: {
    id: 'ai21',
    name: 'AI21 Labs',
    nameEn: 'AI21 Labs',
    baseUrl: 'https://api.ai21.com/v1',
    apiKeyEnv: 'AI21_API_KEY',
    icon: 'brain',
    website: 'https://ai21.com',
    docs: 'https://docs.ai21.com',
    status: 'active',
    categories: ['text'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  aleph: {
    id: 'aleph',
    name: 'Aleph Alpha',
    nameEn: 'Aleph Alpha',
    baseUrl: 'https://api.aleph-alpha.com/v1',
    apiKeyEnv: 'ALEPH_API_KEY',
    icon: 'infinity',
    website: 'https://aleph-alpha.com',
    docs: 'https://docs.aleph-alpha.com',
    status: 'active',
    categories: ['text', 'multimodal'],
    features: {
      streaming: true,
      functionCall: false,
      vision: true,
      audio: false,
      tools: false,
    },
  },
  
  // ============ 更多国内厂商 ============
  
  kimi: {
    id: 'kimi',
    name: 'Kimi (月之暗面)',
    nameEn: 'Kimi',
    baseUrl: 'https://api.moonshot.cn/v1',
    apiKeyEnv: 'MOONSHOT_API_KEY',
    icon: 'moon',
    website: 'https://kimi.moonshot.cn',
    docs: 'https://platform.moonshot.cn/docs',
    status: 'active',
    categories: ['text'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  stepfun: {
    id: 'stepfun',
    name: '阶跃星辰',
    nameEn: 'StepFun',
    baseUrl: 'https://api.stepfun.com/v1',
    apiKeyEnv: 'STEPFUN_API_KEY',
    icon: 'staircase',
    website: 'https://platform.stepfun.com',
    docs: 'https://platform.stepfun.com/docs',
    status: 'active',
    categories: ['text', 'image', 'multimodal'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: false,
      tools: true,
    },
  },
  
  sensenova: {
    id: 'sensenova',
    name: '商汤科技',
    nameEn: 'SenseNova',
    baseUrl: 'https://api.sensenova.cn/v1',
    apiKeyEnv: 'SENSENOVA_API_KEY',
    icon: 'eye',
    website: 'https://platform.sensenova.cn',
    docs: 'https://platform.sensenova.cn/docs',
    status: 'active',
    categories: ['text', 'image', 'multimodal'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: false,
      tools: true,
    },
  },
  
  tencent: {
    id: 'tencent',
    name: '腾讯混元',
    nameEn: 'Tencent Hunyuan',
    baseUrl: 'https://hunyuan.tencentcloudapi.com',
    apiKeyEnv: 'TENCENT_API_KEY',
    icon: 'yin-yang',
    website: 'https://cloud.tencent.com/product/hunyuan',
    docs: 'https://cloud.tencent.com/document/product/1729',
    status: 'active',
    categories: ['text', 'image', 'embedding', 'multimodal'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: false,
      tools: true,
    },
  },
  
  baidu: {
    id: 'baidu',
    name: '百度文心',
    nameEn: 'Baidu Wenxin',
    baseUrl: 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1',
    apiKeyEnv: 'BAIDU_API_KEY',
    icon: 'feather',
    website: 'https://yiyan.baidu.com',
    docs: 'https://cloud.baidu.com/doc/WENXINWORKSHOP',
    status: 'active',
    categories: ['text', 'image'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  360: {
    id: '360',
    name: '360智脑',
    nameEn: '360 Zhinao',
    baseUrl: 'https://api.360.cn/v1',
    apiKeyEnv: '360_API_KEY',
    icon: 'shield-halved',
    website: 'https://ai.360.cn',
    docs: 'https://ai.360.cn/docs',
    status: 'active',
    categories: ['text', 'image'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  siliconflow: {
    id: 'siliconflow',
    name: 'SiliconFlow',
    nameEn: 'SiliconFlow',
    baseUrl: 'https://api.siliconflow.cn/v1',
    apiKeyEnv: 'SILICONFLOW_API_KEY',
    icon: 'microchip',
    website: 'https://siliconflow.cn',
    docs: 'https://docs.siliconflow.cn',
    status: 'active',
    categories: ['text', 'image', 'audio', 'embedding'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: true,
      tools: true,
    },
  },
  
  deepinfra: {
    id: 'deepinfra',
    name: 'DeepInfra',
    nameEn: 'DeepInfra',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    apiKeyEnv: 'DEEPINFRA_API_KEY',
    icon: 'server',
    website: 'https://deepinfra.com',
    docs: 'https://deepinfra.com/docs',
    status: 'active',
    categories: ['text', 'image', 'embedding'],
    features: {
      streaming: true,
      functionCall: true,
      vision: false,
      audio: false,
      tools: true,
    },
  },
  
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    nameEn: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    icon: 'route',
    website: 'https://openrouter.ai',
    docs: 'https://openrouter.ai/docs',
    status: 'active',
    categories: ['text', 'image', 'multimodal'],
    features: {
      streaming: true,
      functionCall: true,
      vision: true,
      audio: false,
      tools: true,
    },
  },
};

// ==================== 模型配置 ====================
// 价格单位：厘/百万tokens（1元 = 1000厘）
// costInputPrice/costOutputPrice = 商家成本价
// sellInputPrice/sellOutputPrice = 平台售价（包含平台服务费）

export const AVAILABLE_MODELS: ModelConfig[] = [
  // ============ OpenAI ============
  {
    id: 'openai-gpt-4o',
    code: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    category: 'multimodal',
    type: 'chat',
    description: 'OpenAI 最新多模态模型，支持文本、图像、音频',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    // 价格单位：厘/千tokens（用户确认：成本 $2.5/$10 每百万tokens）
    costInputPrice: 18,       // 商家成本：$2.5/百万 ≈ 18厘/千
    costOutputPrice: 72,      // 商家成本：$10/百万 ≈ 72厘/千
    platformMarkup: 0.20,     // 平台加价 20%
    sellInputPrice: 22,       // 平台售价：$3/百万 ≈ 22厘/千
    sellOutputPrice: 86,      // 平台售价：$12/百万 ≈ 86厘/千
    features: { streaming: true, functionCall: true, vision: true, audio: true, jsonMode: true },
    status: 'active',
    tags: ['推荐', '多模态', '最新'],
  },
  {
    id: 'openai-gpt-4o-mini',
    code: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    category: 'multimodal',
    type: 'chat',
    description: 'GPT-4o 轻量版，性价比高',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    costInputPrice: 15,
    costOutputPrice: 60,
    platformMarkup: 0.20,
    sellInputPrice: 18,
    sellOutputPrice: 72,
    features: { streaming: true, functionCall: true, vision: true, audio: true, jsonMode: true },
    status: 'active',
    tags: ['性价比', '多模态'],
  },
  {
    id: 'openai-gpt-4-turbo',
    code: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'openai',
    category: 'text',
    type: 'chat',
    description: 'GPT-4 高性能版本',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    costInputPrice: 100,
    costOutputPrice: 300,
    platformMarkup: 0.20,
    sellInputPrice: 120,
    sellOutputPrice: 360,
    features: { streaming: true, functionCall: true, vision: true, audio: false, jsonMode: true },
    status: 'active',
    tags: ['高性能'],
  },
  {
    id: 'openai-gpt-3.5-turbo',
    code: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    provider: 'openai',
    category: 'text',
    type: 'chat',
    description: '经典高性价比模型',
    contextWindow: 16384,
    maxOutputTokens: 4096,
    costInputPrice: 5,
    costOutputPrice: 15,
    platformMarkup: 0.20,
    sellInputPrice: 6,
    sellOutputPrice: 18,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['经典', '便宜'],
  },
  {
    id: 'openai-dall-e-3',
    code: 'dall-e-3',
    name: 'DALL-E 3',
    provider: 'openai',
    category: 'image',
    type: 'image_gen',
    description: 'OpenAI 图像生成模型',
    contextWindow: 0,
    maxOutputTokens: 0,
    // 价格单位：厘/张（用户确认：成本 $40/张，售价 $48/张）
    costInputPrice: 288000,   // 商家成本：$40 ≈ 288000厘
    costOutputPrice: 0,
    platformMarkup: 0.20,     // 平台加价 20%
    sellInputPrice: 345600,   // 平台售价：$48 ≈ 345600厘
    sellOutputPrice: 0,
    features: { streaming: false, functionCall: false, vision: false, audio: false, jsonMode: false },
    status: 'active',
    tags: ['图像生成'],
  },
  {
    id: 'openai-whisper',
    code: 'whisper-1',
    name: 'Whisper',
    provider: 'openai',
    category: 'audio',
    type: 'audio_transcribe',
    description: '语音转文字',
    contextWindow: 0,
    maxOutputTokens: 0,
    costInputPrice: 60,      // ¥0.06/分钟
    costOutputPrice: 0,
    platformMarkup: 0.20,
    sellInputPrice: 72,
    sellOutputPrice: 0,
    features: { streaming: false, functionCall: false, vision: false, audio: true, jsonMode: false },
    status: 'active',
    tags: ['语音识别'],
  },
  {
    id: 'openai-tts',
    code: 'tts-1',
    name: 'TTS-1',
    provider: 'openai',
    category: 'audio',
    type: 'audio_tts',
    description: '文字转语音',
    contextWindow: 0,
    maxOutputTokens: 0,
    costInputPrice: 150,
    costOutputPrice: 0,
    platformMarkup: 0.20,
    sellInputPrice: 180,
    sellOutputPrice: 0,
    features: { streaming: true, functionCall: false, vision: false, audio: true, jsonMode: false },
    status: 'active',
    tags: ['语音合成'],
  },
  
  // ============ Anthropic ============
  {
    id: 'anthropic-claude-3-5-sonnet',
    code: 'claude-3-5-sonnet-20241022',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    category: 'multimodal',
    type: 'chat',
    description: 'Anthropic 最新旗舰模型',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    // 价格单位：厘/千tokens（用户确认：成本 $3/$15 每百万tokens）
    costInputPrice: 22,       // 商家成本：$3/百万 ≈ 22厘/千
    costOutputPrice: 108,     // 商家成本：$15/百万 ≈ 108厘/千
    platformMarkup: 0.20,     // 平台加价 20%
    sellInputPrice: 26,       // 平台售价：$3.6/百万 ≈ 26厘/千
    sellOutputPrice: 130,     // 平台售价：$18/百万 ≈ 130厘/千
    features: { streaming: true, functionCall: true, vision: true, audio: false, jsonMode: true },
    status: 'active',
    tags: ['推荐', '旗舰', '长上下文'],
  },
  {
    id: 'anthropic-claude-3-opus',
    code: 'claude-3-opus-20240229',
    name: 'Claude 3 Opus',
    provider: 'anthropic',
    category: 'multimodal',
    type: 'chat',
    description: 'Anthropic 最强模型',
    contextWindow: 200000,
    maxOutputTokens: 4096,
    costInputPrice: 1500,
    costOutputPrice: 7500,
    platformMarkup: 0.20,
    sellInputPrice: 1800,
    sellOutputPrice: 9000,
    features: { streaming: true, functionCall: true, vision: true, audio: false, jsonMode: true },
    status: 'active',
    tags: ['顶级', '长上下文'],
  },
  {
    id: 'anthropic-claude-3-haiku',
    code: 'claude-3-haiku-20240307',
    name: 'Claude 3 Haiku',
    provider: 'anthropic',
    category: 'text',
    type: 'chat',
    description: 'Claude 轻量快速版',
    contextWindow: 200000,
    maxOutputTokens: 4096,
    costInputPrice: 25,
    costOutputPrice: 125,
    platformMarkup: 0.20,
    sellInputPrice: 30,
    sellOutputPrice: 150,
    features: { streaming: true, functionCall: true, vision: true, audio: false, jsonMode: true },
    status: 'active',
    tags: ['快速', '便宜'],
  },
  
  // ============ Google ============
  {
    id: 'google-gemini-2-flash',
    code: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    category: 'multimodal',
    type: 'chat',
    description: 'Google 最新多模态模型（）',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    // 价格单位：厘/千tokens（用户确认：，平台 $0.05/$0.05 每百万tokens）
    costInputPrice: 0,        // 
    costOutputPrice: 0,
    platformMarkup: 0.50,     // 平台服务费比例
    sellInputPrice: 0.4,      // 平台售价：$0.05/百万 ≈ 0.4厘/千
    sellOutputPrice: 0.4,
    features: { streaming: true, functionCall: true, vision: true, audio: true, jsonMode: true },
    status: 'active',
    tags: ['推荐', '免费额度', '超长上下文'],
  },
  {
    id: 'google-gemini-1-5-pro',
    code: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'google',
    category: 'multimodal',
    type: 'chat',
    description: 'Google 专业版模型',
    contextWindow: 2000000,
    maxOutputTokens: 8192,
    costInputPrice: 175,
    costOutputPrice: 700,
    platformMarkup: 0.20,
    sellInputPrice: 210,
    sellOutputPrice: 840,
    features: { streaming: true, functionCall: true, vision: true, audio: true, jsonMode: true },
    status: 'active',
    tags: ['专业', '超长上下文'],
  },
  {
    id: 'google-gemini-1-5-flash',
    code: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'google',
    category: 'multimodal',
    type: 'chat',
    description: 'Google 快速版模型',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    costInputPrice: 35,
    costOutputPrice: 105,
    platformMarkup: 0.20,
    sellInputPrice: 42,
    sellOutputPrice: 126,
    features: { streaming: true, functionCall: true, vision: true, audio: true, jsonMode: true },
    status: 'active',
    tags: ['快速', '长上下文'],
  },
  
  // ============ DeepSeek ============
  {
    id: 'deepseek-chat',
    code: 'deepseek-chat',
    name: 'DeepSeek V3 (免费)',
    provider: 'deepseek',
    category: 'text',
    type: 'chat',
    description: 'DeepSeek V3 对话模型（）',
    contextWindow: 64000,
    maxOutputTokens: 4096,
    // 价格单位：厘/千tokens（用户确认：，平台 $0.1/$0.1 每百万tokens）
    costInputPrice: 0,        // 
    costOutputPrice: 0,
    platformMarkup: 0.20,     // 平台服务费比例
    sellInputPrice: 0.7,      // 平台售价：$0.1/百万 ≈ 0.7厘/千
    sellOutputPrice: 0.7,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['性价比', '国产', '免费额度'],
  },
  {
    id: 'deepseek-reasoner',
    code: 'deepseek-reasoner',
    name: 'DeepSeek R1',
    provider: 'deepseek',
    category: 'text',
    type: 'chat',
    description: 'DeepSeek 推理模型',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    costInputPrice: 55,
    costOutputPrice: 220,
    platformMarkup: 0.20,
    sellInputPrice: 66,
    sellOutputPrice: 264,
    features: { streaming: true, functionCall: false, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['推理', '国产'],
  },
  
  // ============ Groq (极速推理) ============
  {
    id: 'groq-llama-3-3-70b',
    code: 'llama-3.3-70b-versatile',
    name: 'Llama 3.3 70B',
    provider: 'groq',
    category: 'text',
    type: 'chat',
    description: 'Groq 极速推理 Llama 模型',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costInputPrice: 60,
    costOutputPrice: 60,
    platformMarkup: 0.20,
    sellInputPrice: 72,
    sellOutputPrice: 72,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['极速', '开源'],
  },
  {
    id: 'groq-llama-3-2-90b',
    code: 'llama-3.2-90b-vision-preview',
    name: 'Llama 3.2 90B Vision',
    provider: 'groq',
    category: 'multimodal',
    type: 'chat',
    description: 'Groq 多模态 Llama 模型',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costInputPrice: 90,
    costOutputPrice: 90,
    platformMarkup: 0.20,
    sellInputPrice: 108,
    sellOutputPrice: 108,
    features: { streaming: true, functionCall: true, vision: true, audio: false, jsonMode: true },
    status: 'active',
    tags: ['极速', '多模态', '开源'],
  },
  {
    id: 'groq-whisper',
    code: 'whisper-large-v3',
    name: 'Whisper Large V3',
    provider: 'groq',
    category: 'audio',
    type: 'audio_transcribe',
    description: 'Groq 极速语音识别',
    contextWindow: 0,
    maxOutputTokens: 0,
    costInputPrice: 20,
    costOutputPrice: 0,
    platformMarkup: 0.20,
    sellInputPrice: 24,
    sellOutputPrice: 0,
    features: { streaming: false, functionCall: false, vision: false, audio: true, jsonMode: false },
    status: 'active',
    tags: ['极速', '语音识别'],
  },
  
  // ============ Mistral ============
  {
    id: 'mistral-large',
    code: 'mistral-large-latest',
    name: 'Mistral Large',
    provider: 'mistral',
    category: 'text',
    type: 'chat',
    description: 'Mistral 旗舰模型',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costInputPrice: 200,
    costOutputPrice: 600,
    platformMarkup: 0.20,
    sellInputPrice: 240,
    sellOutputPrice: 720,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['旗舰', '欧洲'],
  },
  {
    id: 'mistral-small',
    code: 'mistral-small-latest',
    name: 'Mistral Small',
    provider: 'mistral',
    category: 'text',
    type: 'chat',
    description: 'Mistral 轻量模型',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costInputPrice: 20,
    costOutputPrice: 60,
    platformMarkup: 0.20,
    sellInputPrice: 24,
    sellOutputPrice: 72,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['便宜', '欧洲'],
  },
  {
    id: 'mistral-pixtral',
    code: 'pixtral-12b-2409',
    name: 'Pixtral 12B',
    provider: 'mistral',
    category: 'multimodal',
    type: 'chat',
    description: 'Mistral 多模态模型',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costInputPrice: 15,
    costOutputPrice: 15,
    platformMarkup: 0.20,
    sellInputPrice: 18,
    sellOutputPrice: 18,
    features: { streaming: true, functionCall: false, vision: true, audio: false, jsonMode: false },
    status: 'active',
    tags: ['多模态', '便宜'],
  },
  
  // ============ Cohere ============
  {
    id: 'cohere-command-r-plus',
    code: 'command-r-plus',
    name: 'Command R+',
    provider: 'cohere',
    category: 'text',
    type: 'chat',
    description: 'Cohere 检索增强模型',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    costInputPrice: 30,
    costOutputPrice: 150,
    platformMarkup: 0.20,
    sellInputPrice: 36,
    sellOutputPrice: 180,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['RAG', '长上下文'],
  },
  {
    id: 'cohere-embed',
    code: 'embed-english-v3.0',
    name: 'Cohere Embed',
    provider: 'cohere',
    category: 'embedding',
    type: 'embedding',
    description: 'Cohere 文本嵌入模型',
    contextWindow: 512,
    maxOutputTokens: 0,
    costInputPrice: 10,
    costOutputPrice: 0,
    platformMarkup: 0.10,
    sellInputPrice: 11,
    sellOutputPrice: 0,
    features: { streaming: false, functionCall: false, vision: false, audio: false, jsonMode: false },
    status: 'active',
    tags: ['嵌入'],
  },
  
  // ============ Stability AI ============
  {
    id: 'stability-sd-3',
    code: 'stable-diffusion-3',
    name: 'Stable Diffusion 3',
    provider: 'stability',
    category: 'image',
    type: 'image_gen',
    description: 'Stability AI 图像生成',
    contextWindow: 0,
    maxOutputTokens: 0,
    costInputPrice: 350,
    costOutputPrice: 0,
    platformMarkup: 0.25,
    sellInputPrice: 438,
    sellOutputPrice: 0,
    features: { streaming: false, functionCall: false, vision: false, audio: false, jsonMode: false },
    status: 'active',
    tags: ['图像生成', '开源'],
  },
  
  // ============ 豆包 ============
  {
    id: 'doubao-pro-128k',
    code: 'doubao-pro-128k',
    name: '豆包 Pro 128K',
    provider: 'doubao',
    category: 'text',
    type: 'chat',
    description: '字节豆包专业版',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    costInputPrice: 50,
    costOutputPrice: 50,
    platformMarkup: 0.15,
    sellInputPrice: 58,
    sellOutputPrice: 58,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '长上下文'],
  },
  {
    id: 'doubao-lite-4k',
    code: 'doubao-lite-4k',
    name: '豆包 Lite',
    provider: 'doubao',
    category: 'text',
    type: 'chat',
    description: '字节豆包轻量版',
    contextWindow: 4096,
    maxOutputTokens: 2048,
    costInputPrice: 3,
    costOutputPrice: 3,
    platformMarkup: 0.15,
    sellInputPrice: 4,
    sellOutputPrice: 4,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '超便宜'],
  },
  {
    id: 'doubao-vision',
    code: 'doubao-vision-pro-32k',
    name: '豆包 Vision',
    provider: 'doubao',
    category: 'multimodal',
    type: 'chat',
    description: '豆包多模态模型',
    contextWindow: 32000,
    maxOutputTokens: 4096,
    costInputPrice: 80,
    costOutputPrice: 80,
    platformMarkup: 0.15,
    sellInputPrice: 92,
    sellOutputPrice: 92,
    features: { streaming: true, functionCall: false, vision: true, audio: false, jsonMode: false },
    status: 'active',
    tags: ['国产', '多模态'],
  },
  
  // ============ 通义千问 ============
  {
    id: 'qwen-max',
    code: 'qwen-max',
    name: '通义千问 Max',
    provider: 'qwen',
    category: 'multimodal',
    type: 'chat',
    description: '阿里通义千问旗舰版',
    contextWindow: 32768,
    maxOutputTokens: 8192,
    costInputPrice: 200,
    costOutputPrice: 600,
    platformMarkup: 0.15,
    sellInputPrice: 230,
    sellOutputPrice: 690,
    features: { streaming: true, functionCall: true, vision: true, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '旗舰'],
  },
  {
    id: 'qwen-plus',
    code: 'qwen-plus',
    name: '通义千问 Plus',
    provider: 'qwen',
    category: 'text',
    type: 'chat',
    description: '阿里通义千问增强版',
    contextWindow: 128000,
    maxOutputTokens: 6144,
    costInputPrice: 40,
    costOutputPrice: 120,
    platformMarkup: 0.15,
    sellInputPrice: 46,
    sellOutputPrice: 138,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '长上下文'],
  },
  {
    id: 'qwen-turbo',
    code: 'qwen-turbo',
    name: '通义千问 Turbo',
    provider: 'qwen',
    category: 'text',
    type: 'chat',
    description: '阿里通义千问快速版',
    contextWindow: 128000,
    maxOutputTokens: 6144,
    costInputPrice: 30,
    costOutputPrice: 60,
    platformMarkup: 0.15,
    sellInputPrice: 35,
    sellOutputPrice: 69,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '快速'],
  },
  {
    id: 'qwen-vl-max',
    code: 'qwen-vl-max',
    name: '通义千问 VL Max',
    provider: 'qwen',
    category: 'multimodal',
    type: 'chat',
    description: '通义千问视觉模型',
    contextWindow: 32768,
    maxOutputTokens: 8192,
    costInputPrice: 200,
    costOutputPrice: 600,
    platformMarkup: 0.15,
    sellInputPrice: 230,
    sellOutputPrice: 690,
    features: { streaming: true, functionCall: false, vision: true, audio: false, jsonMode: false },
    status: 'active',
    tags: ['国产', '多模态'],
  },
  {
    id: 'qwen-wanx',
    code: 'wanx-v1',
    name: '通义万相',
    provider: 'qwen',
    category: 'image',
    type: 'image_gen',
    description: '阿里图像生成模型',
    contextWindow: 0,
    maxOutputTokens: 0,
    costInputPrice: 80,
    costOutputPrice: 0,
    platformMarkup: 0.25,
    sellInputPrice: 100,
    sellOutputPrice: 0,
    features: { streaming: false, functionCall: false, vision: false, audio: false, jsonMode: false },
    status: 'active',
    tags: ['国产', '图像生成'],
  },
  
  // ============ 文心一言 ============
  {
    id: 'wenxin-4-8k',
    code: 'ernie-4.0-8k',
    name: '文心一言 4.0',
    provider: 'wenxin',
    category: 'text',
    type: 'chat',
    description: '百度文心一言旗舰版',
    contextWindow: 8192,
    maxOutputTokens: 4096,
    costInputPrice: 120,
    costOutputPrice: 120,
    platformMarkup: 0.15,
    sellInputPrice: 138,
    sellOutputPrice: 138,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '旗舰'],
  },
  {
    id: 'wenxin-3-5-4k',
    code: 'ernie-3.5-4k',
    name: '文心一言 3.5',
    provider: 'wenxin',
    category: 'text',
    type: 'chat',
    description: '百度文心一言标准版',
    contextWindow: 4096,
    maxOutputTokens: 2048,
    costInputPrice: 40,
    costOutputPrice: 80,
    platformMarkup: 0.15,
    sellInputPrice: 46,
    sellOutputPrice: 92,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产'],
  },
  {
    id: 'wenxin-speed',
    code: 'ernie-speed-8k',
    name: '文心一言 Speed',
    provider: 'wenxin',
    category: 'text',
    type: 'chat',
    description: '百度文心一言快速版',
    contextWindow: 8192,
    maxOutputTokens: 4096,
    costInputPrice: 4,
    costOutputPrice: 4,
    platformMarkup: 0.15,
    sellInputPrice: 5,
    sellOutputPrice: 5,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '便宜'],
  },
  
  // ============ 智谱AI ============
  {
    id: 'zhipu-glm-4-plus',
    code: 'glm-4-plus',
    name: 'GLM-4 Plus',
    provider: 'zhipu',
    category: 'text',
    type: 'chat',
    description: '智谱GLM-4增强版',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    costInputPrice: 500,
    costOutputPrice: 500,
    platformMarkup: 0.15,
    sellInputPrice: 575,
    sellOutputPrice: 575,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '长上下文'],
  },
  {
    id: 'zhipu-glm-4-flash',
    code: 'glm-4-flash',
    name: 'GLM-4 Flash',
    provider: 'zhipu',
    category: 'text',
    type: 'chat',
    description: '智谱GLM-4快速版',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    costInputPrice: 10,
    costOutputPrice: 10,
    platformMarkup: 0.15,
    sellInputPrice: 12,
    sellOutputPrice: 12,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '便宜'],
  },
  {
    id: 'zhipu-glm-4v',
    code: 'glm-4v',
    name: 'GLM-4V',
    provider: 'zhipu',
    category: 'multimodal',
    type: 'chat',
    description: '智谱多模态模型',
    contextWindow: 8192,
    maxOutputTokens: 4096,
    costInputPrice: 100,
    costOutputPrice: 100,
    platformMarkup: 0.15,
    sellInputPrice: 115,
    sellOutputPrice: 115,
    features: { streaming: true, functionCall: false, vision: true, audio: false, jsonMode: false },
    status: 'active',
    tags: ['国产', '多模态'],
  },
  {
    id: 'zhipu-cogview-3',
    code: 'cogview-3',
    name: 'CogView 3',
    provider: 'zhipu',
    category: 'image',
    type: 'image_gen',
    description: '智谱图像生成模型',
    contextWindow: 0,
    maxOutputTokens: 0,
    costInputPrice: 80,
    costOutputPrice: 0,
    platformMarkup: 0.25,
    sellInputPrice: 100,
    sellOutputPrice: 0,
    features: { streaming: false, functionCall: false, vision: false, audio: false, jsonMode: false },
    status: 'active',
    tags: ['国产', '图像生成'],
  },
  
  // ============ Moonshot (Kimi) ============
  {
    id: 'moonshot-v1-8k',
    code: 'moonshot-v1-8k',
    name: 'Kimi',
    provider: 'moonshot',
    category: 'text',
    type: 'chat',
    description: '月之暗面 Kimi 对话模型',
    contextWindow: 8192,
    maxOutputTokens: 4096,
    costInputPrice: 120,
    costOutputPrice: 120,
    platformMarkup: 0.15,
    sellInputPrice: 138,
    sellOutputPrice: 138,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '长文本'],
  },
  {
    id: 'moonshot-v1-32k',
    code: 'moonshot-v1-32k',
    name: 'Kimi 32K',
    provider: 'moonshot',
    category: 'text',
    type: 'chat',
    description: 'Kimi 长文本版',
    contextWindow: 32768,
    maxOutputTokens: 4096,
    costInputPrice: 240,
    costOutputPrice: 240,
    platformMarkup: 0.15,
    sellInputPrice: 276,
    sellOutputPrice: 276,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '长文本'],
  },
  {
    id: 'moonshot-v1-128k',
    code: 'moonshot-v1-128k',
    name: 'Kimi 128K',
    provider: 'moonshot',
    category: 'text',
    type: 'chat',
    description: 'Kimi 超长文本版',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    costInputPrice: 600,
    costOutputPrice: 600,
    platformMarkup: 0.15,
    sellInputPrice: 690,
    sellOutputPrice: 690,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '超长文本'],
  },
  
  // ============ MiniMax ============
  {
    id: 'minimax-abab6-5-chat',
    code: 'abab6.5-chat',
    name: '海螺 AI',
    provider: 'minimax',
    category: 'text',
    type: 'chat',
    description: 'MiniMax 海螺AI',
    contextWindow: 245000,
    maxOutputTokens: 8192,
    costInputPrice: 300,
    costOutputPrice: 300,
    platformMarkup: 0.15,
    sellInputPrice: 345,
    sellOutputPrice: 345,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '超长上下文'],
  },
  {
    id: 'minimax-abab5-5-chat',
    code: 'abab5.5-chat',
    name: '海螺 AI Lite',
    provider: 'minimax',
    category: 'text',
    type: 'chat',
    description: 'MiniMax 海螺AI轻量版',
    contextWindow: 16384,
    maxOutputTokens: 4096,
    costInputPrice: 150,
    costOutputPrice: 150,
    platformMarkup: 0.15,
    sellInputPrice: 173,
    sellOutputPrice: 173,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产'],
  },
  {
    id: 'minimax-video',
    code: 'video-01',
    name: '海螺视频',
    provider: 'minimax',
    category: 'video',
    type: 'video_gen',
    description: 'MiniMax 视频生成',
    contextWindow: 0,
    maxOutputTokens: 0,
    costInputPrice: 5000,    // ¥5/视频
    costOutputPrice: 0,
    platformMarkup: 0.30,
    sellInputPrice: 6500,
    sellOutputPrice: 0,
    features: { streaming: false, functionCall: false, vision: false, audio: false, jsonMode: false },
    status: 'active',
    tags: ['国产', '视频生成'],
  },
  
  // ============ 讯飞星火 ============
  {
    id: 'spark-v3-5',
    code: 'generalv3.5',
    name: '星火 3.5',
    provider: 'spark',
    category: 'text',
    type: 'chat',
    description: '讯飞星火3.5',
    contextWindow: 8192,
    maxOutputTokens: 4096,
    costInputPrice: 30,
    costOutputPrice: 30,
    platformMarkup: 0.15,
    sellInputPrice: 35,
    sellOutputPrice: 35,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产'],
  },
  {
    id: 'spark-v4',
    code: 'generalv4',
    name: '星火 4.0',
    provider: 'spark',
    category: 'text',
    type: 'chat',
    description: '讯飞星火4.0旗舰版',
    contextWindow: 8192,
    maxOutputTokens: 4096,
    costInputPrice: 100,
    costOutputPrice: 100,
    platformMarkup: 0.15,
    sellInputPrice: 115,
    sellOutputPrice: 115,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '旗舰'],
  },
  {
    id: 'spark-lite',
    code: 'general-lite',
    name: '星火 Lite',
    provider: 'spark',
    category: 'text',
    type: 'chat',
    description: '讯飞星火轻量版',
    contextWindow: 4096,
    maxOutputTokens: 2048,
    costInputPrice: 2,
    costOutputPrice: 2,
    platformMarkup: 0.15,
    sellInputPrice: 3,
    sellOutputPrice: 3,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '便宜'],
  },
  
  // ============ 腾讯混元 ============
  {
    id: 'hunyuan-lite',
    code: 'hunyuan-lite',
    name: '混元 Lite',
    provider: 'hunyuan',
    category: 'text',
    type: 'chat',
    description: '腾讯混元轻量版',
    contextWindow: 256000,
    maxOutputTokens: 6144,
    costInputPrice: 3,
    costOutputPrice: 3,
    platformMarkup: 0.15,
    sellInputPrice: 4,
    sellOutputPrice: 4,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '便宜', '超长上下文'],
  },
  {
    id: 'hunyuan-pro',
    code: 'hunyuan-pro',
    name: '混元 Pro',
    provider: 'hunyuan',
    category: 'text',
    type: 'chat',
    description: '腾讯混元专业版',
    contextWindow: 32000,
    maxOutputTokens: 4096,
    costInputPrice: 40,
    costOutputPrice: 40,
    platformMarkup: 0.15,
    sellInputPrice: 46,
    sellOutputPrice: 46,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产'],
  },
  {
    id: 'hunyuan-vision',
    code: 'hunyuan-vision',
    name: '混元 Vision',
    provider: 'hunyuan',
    category: 'multimodal',
    type: 'chat',
    description: '腾讯混元视觉模型',
    contextWindow: 8192,
    maxOutputTokens: 4096,
    costInputPrice: 80,
    costOutputPrice: 80,
    platformMarkup: 0.15,
    sellInputPrice: 92,
    sellOutputPrice: 92,
    features: { streaming: true, functionCall: false, vision: true, audio: false, jsonMode: false },
    status: 'active',
    tags: ['国产', '多模态'],
  },
  
  // ============ 零一万物 ============
  {
    id: 'yi-large',
    code: 'yi-large',
    name: 'Yi Large',
    provider: 'yi',
    category: 'text',
    type: 'chat',
    description: '零一万物大模型',
    contextWindow: 32768,
    maxOutputTokens: 4096,
    costInputPrice: 200,
    costOutputPrice: 200,
    platformMarkup: 0.15,
    sellInputPrice: 230,
    sellOutputPrice: 230,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产'],
  },
  {
    id: 'yi-medium',
    code: 'yi-medium',
    name: 'Yi Medium',
    provider: 'yi',
    category: 'text',
    type: 'chat',
    description: '零一万物中型模型',
    contextWindow: 16384,
    maxOutputTokens: 4096,
    costInputPrice: 25,
    costOutputPrice: 25,
    platformMarkup: 0.15,
    sellInputPrice: 29,
    sellOutputPrice: 29,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '便宜'],
  },
  {
    id: 'yi-vision',
    code: 'yi-vision',
    name: 'Yi Vision',
    provider: 'yi',
    category: 'multimodal',
    type: 'chat',
    description: '零一万物视觉模型',
    contextWindow: 16384,
    maxOutputTokens: 4096,
    costInputPrice: 60,
    costOutputPrice: 60,
    platformMarkup: 0.15,
    sellInputPrice: 69,
    sellOutputPrice: 69,
    features: { streaming: true, functionCall: false, vision: true, audio: false, jsonMode: false },
    status: 'active',
    tags: ['国产', '多模态'],
  },
  
  // ============ 百川 ============
  {
    id: 'baichuan-4',
    code: 'Baichuan4',
    name: '百川 4',
    provider: 'baichuan',
    category: 'text',
    type: 'chat',
    description: '百川智能旗舰模型',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    costInputPrice: 100,
    costOutputPrice: 100,
    platformMarkup: 0.15,
    sellInputPrice: 115,
    sellOutputPrice: 115,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '长上下文'],
  },
  {
    id: 'baichuan-3-turbo',
    code: 'Baichuan3-Turbo',
    name: '百川 3 Turbo',
    provider: 'baichuan',
    category: 'text',
    type: 'chat',
    description: '百川智能快速版',
    contextWindow: 32000,
    maxOutputTokens: 4096,
    costInputPrice: 12,
    costOutputPrice: 12,
    platformMarkup: 0.15,
    sellInputPrice: 14,
    sellOutputPrice: 14,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['国产', '便宜'],
  },
  
  // ============ 免费模型（）============
  // 这些模型商家提供免费额度，但平台仍收取少量服务费
  
  // --- Groq 免费模型 ---
  {
    id: 'groq-llama-3-3-70b-free',
    code: 'llama-3.3-70b-versatile',
    name: 'Llama 3.3 70B (免费)',
    provider: 'groq',
    category: 'text',
    type: 'chat',
    description: 'Groq 极速推理 - ',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costInputPrice: 0,         // 
    costOutputPrice: 0,        // 
    platformMarkup: 1.0,       // 平台加价100%（纯服务费）
    sellInputPrice: 5,         // 平台收费：¥0.005/千tokens
    sellOutputPrice: 5,        // 平台收费：¥0.005/千tokens
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '极速', '推荐'],
  },
  {
    id: 'groq-llama-3-2-1b-free',
    code: 'llama-3.2-1b-preview',
    name: 'Llama 3.2 1B (免费)',
    provider: 'groq',
    category: 'text',
    type: 'chat',
    description: 'Groq 轻量模型 - ',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 1.0,
    sellInputPrice: 2,
    sellOutputPrice: 2,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '极速'],
  },
  {
    id: 'groq-llama-3-2-3b-free',
    code: 'llama-3.2-3b-preview',
    name: 'Llama 3.2 3B (免费)',
    provider: 'groq',
    category: 'text',
    type: 'chat',
    description: 'Groq 中型模型 - ',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 1.0,
    sellInputPrice: 3,
    sellOutputPrice: 3,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '极速'],
  },
  {
    id: 'groq-mixtral-8x7b-free',
    code: 'mixtral-8x7b-32768',
    name: 'Mixtral 8x7B (免费)',
    provider: 'groq',
    category: 'text',
    type: 'chat',
    description: 'Groq Mixtral模型 - ',
    contextWindow: 32768,
    maxOutputTokens: 8192,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 1.0,
    sellInputPrice: 4,
    sellOutputPrice: 4,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '极速'],
  },
  {
    id: 'groq-gemma-2-9b-free',
    code: 'gemma2-9b-it',
    name: 'Gemma 2 9B (免费)',
    provider: 'groq',
    category: 'text',
    type: 'chat',
    description: 'Google Gemma 2 - ',
    contextWindow: 8192,
    maxOutputTokens: 8192,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 1.0,
    sellInputPrice: 3,
    sellOutputPrice: 3,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '极速'],
  },
  
  // --- Google 免费模型 ---
  {
    id: 'google-gemini-2-flash-free',
    code: 'gemini-2.0-flash-exp',
    name: 'Gemini 2.0 Flash (免费)',
    provider: 'google',
    category: 'multimodal',
    type: 'chat',
    description: 'Google 最新多模态 - 免费体验',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 0.5,       // 平台收取50%服务费
    sellInputPrice: 3,
    sellOutputPrice: 3,
    features: { streaming: true, functionCall: true, vision: true, audio: true, jsonMode: true },
    status: 'active',
    tags: ['免费', '多模态', '推荐'],
  },
  {
    id: 'google-gemini-1-5-flash-free',
    code: 'gemini-1.5-flash-8b',
    name: 'Gemini 1.5 Flash 8B (免费)',
    provider: 'google',
    category: 'multimodal',
    type: 'chat',
    description: 'Google 轻量多模态 - 免费体验',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 0.5,
    sellInputPrice: 2,
    sellOutputPrice: 2,
    features: { streaming: true, functionCall: true, vision: true, audio: true, jsonMode: true },
    status: 'active',
    tags: ['免费', '多模态'],
  },
  
  // --- DeepSeek 免费时段 ---
  {
    id: 'deepseek-chat-free',
    code: 'deepseek-chat',
    name: 'DeepSeek Chat (免费)',
    provider: 'deepseek',
    category: 'text',
    type: 'chat',
    description: 'DeepSeek 对话模型 - 限时免费',
    contextWindow: 64000,
    maxOutputTokens: 4096,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 0.3,
    sellInputPrice: 3,
    sellOutputPrice: 3,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '性价比'],
  },
  
  // --- 国产免费模型 ---
  {
    id: 'zhipu-glm-4-flash-free',
    code: 'glm-4-flash',
    name: 'GLM-4 Flash (免费)',
    provider: 'zhipu',
    category: 'text',
    type: 'chat',
    description: '智谱快速版 - 免费体验',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 0.3,
    sellInputPrice: 3,
    sellOutputPrice: 3,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '国产', '长上下文'],
  },
  {
    id: 'qwen-turbo-free',
    code: 'qwen-turbo-latest',
    name: '通义千问 Turbo (免费)',
    provider: 'qwen',
    category: 'text',
    type: 'chat',
    description: '阿里通义快速版 - 免费体验',
    contextWindow: 128000,
    maxOutputTokens: 6144,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 0.3,
    sellInputPrice: 3,
    sellOutputPrice: 3,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '国产', '长上下文'],
  },
  {
    id: 'doubao-lite-free',
    code: 'doubao-lite-4k',
    name: '豆包 Lite (免费)',
    provider: 'doubao',
    category: 'text',
    type: 'chat',
    description: '字节豆包轻量版 - 免费体验',
    contextWindow: 4096,
    maxOutputTokens: 2048,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 0.3,
    sellInputPrice: 2,
    sellOutputPrice: 2,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '国产'],
  },
  {
    id: 'hunyuan-lite-free',
    code: 'hunyuan-lite',
    name: '混元 Lite (免费)',
    provider: 'hunyuan',
    category: 'text',
    type: 'chat',
    description: '腾讯混元轻量版 - 免费体验',
    contextWindow: 256000,
    maxOutputTokens: 6144,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 0.3,
    sellInputPrice: 2,
    sellOutputPrice: 2,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '国产', '超长上下文'],
  },
  {
    id: 'wenxin-speed-free',
    code: 'ernie-speed-8k',
    name: '文心 Speed (免费)',
    provider: 'wenxin',
    category: 'text',
    type: 'chat',
    description: '百度文心快速版 - 免费体验',
    contextWindow: 8192,
    maxOutputTokens: 4096,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 0.3,
    sellInputPrice: 2,
    sellOutputPrice: 2,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '国产'],
  },
  {
    id: 'spark-lite-free',
    code: 'general-lite',
    name: '星火 Lite (免费)',
    provider: 'spark',
    category: 'text',
    type: 'chat',
    description: '讯飞星火轻量版 - 免费体验',
    contextWindow: 4096,
    maxOutputTokens: 2048,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 0.3,
    sellInputPrice: 2,
    sellOutputPrice: 2,
    features: { streaming: true, functionCall: true, vision: false, audio: false, jsonMode: true },
    status: 'active',
    tags: ['免费', '国产'],
  },
  
  // --- Groq 免费语音识别 ---
  {
    id: 'groq-whisper-free',
    code: 'whisper-large-v3-turbo',
    name: 'Whisper Turbo (免费)',
    provider: 'groq',
    category: 'audio',
    type: 'audio_transcribe',
    description: 'Groq 极速语音识别 - ',
    contextWindow: 0,
    maxOutputTokens: 0,
    costInputPrice: 0,
    costOutputPrice: 0,
    platformMarkup: 0.5,
    sellInputPrice: 10,        // ¥0.01/分钟
    sellOutputPrice: 0,
    features: { streaming: false, functionCall: false, vision: false, audio: true, jsonMode: false },
    status: 'active',
    tags: ['免费', '极速', '语音识别'],
  },
];

// ==================== 辅助函数 ====================

/**
 * 获取提供商的API密钥
 */
export function getProviderApiKey(providerId: string): string | undefined {
  const provider = MODEL_PROVIDERS[providerId];
  if (!provider) return undefined;
  return process.env[provider.apiKeyEnv];
}

/**
 * 检查提供商是否可用
 */
export function isProviderAvailable(providerId: string): boolean {
  const apiKey = getProviderApiKey(providerId);
  return !!apiKey;
}

/**
 * 获取可用的模型列表
 */
export function getAvailableModels(): ModelConfig[] {
  return AVAILABLE_MODELS.filter(model => {
    return isProviderAvailable(model.provider);
  });
}

/**
 * 根据类别获取模型
 */
export function getModelsByCategory(category: string): ModelConfig[] {
  return AVAILABLE_MODELS.filter(model => model.category === category);
}

/**
 * 根据提供商获取模型
 */
export function getModelsByProvider(providerId: string): ModelConfig[] {
  return AVAILABLE_MODELS.filter(model => model.provider === providerId);
}

/**
 * 计算平台利润
 */
export function calculatePlatformProfit(
  model: ModelConfig,
  inputTokens: number,
  outputTokens: number
): { cost: number; revenue: number; profit: number } {
  const cost = (model.costInputPrice * inputTokens + model.costOutputPrice * outputTokens) / 1000000;
  const revenue = (model.sellInputPrice * inputTokens + model.sellOutputPrice * outputTokens) / 1000000;
  const profit = revenue - cost;
  
  return {
    cost: Math.round(cost * 1000) / 1000,    // 保留3位小数
    revenue: Math.round(revenue * 1000) / 1000,
    profit: Math.round(profit * 1000) / 1000,
  };
}

/**
 * 获取模型定价信息（返回给前端）
 */
export function getModelPricing(model: ModelConfig) {
  return {
    code: model.code,
    name: model.name,
    provider: model.provider,
    category: model.category,
    // 价格单位转换为元/百万tokens
    inputPrice: model.sellInputPrice / 1000,
    outputPrice: model.sellOutputPrice / 1000,
    // 显示格式化价格
    inputPriceDisplay: formatPrice(model.sellInputPrice),
    outputPriceDisplay: formatPrice(model.sellOutputPrice),
    // 平台加价比例
    platformMarkup: model.platformMarkup,
    platformMarkupPercent: `${Math.round(model.platformMarkup * 100)}%`,
  };
}

/**
 * 格式化价格显示
 */
function formatPrice(priceInLi: number): string {
  if (priceInLi === 0) return '免费';
  const priceInYuan = priceInLi / 1000;
  if (priceInYuan < 0.01) return `¥${(priceInYuan * 100).toFixed(2)}/万tokens`;
  if (priceInYuan < 1) return `¥${priceInYuan.toFixed(3)}/千tokens`;
  return `¥${priceInYuan.toFixed(2)}/百万tokens`;
}
